//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public string caddress { get; set; }
        public string cemail { get; set; }
        public string ccno { get; set; }
        public Nullable<double> cpackage { get; set; }
        public string cjobprofile { get; set; }
        public Nullable<int> crequiremet { get; set; }
        public Nullable<System.DateTime> cdateofdrive { get; set; }
    }
}
