//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string sid { get; set; }
        public string sname { get; set; }
        public string sgender { get; set; }
        public string scno { get; set; }
        public string semail { get; set; }
        public string spassword { get; set; }
        public Nullable<System.DateTime> sdob { get; set; }
        public string saddress { get; set; }
        public Nullable<double> sssc { get; set; }
        public Nullable<double> shsc { get; set; }
        public Nullable<double> scpi { get; set; }
        public Nullable<double> sspi { get; set; }
        public string sskill { get; set; }
        public string srollno { get; set; }
        public string sbranch { get; set; }
        public Nullable<int> ssem { get; set; }
        public string stype { get; set; }
        public Nullable<int> srank { get; set; }
    }
}
